language: haskell
env:
  #- GHCVER=7.8.1
  - GHCVER=7.10.1
  # doctest doesnt build with ghc 8.* yet
  #- GHCVER=head

branches:
    only:
        -   master

notifications:
  webhooks:
    urls:
        -   https://webhooks.gitter.im/e/e80ceb37bab1d58c4128
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_install:
  # If $GHCVER is the one travis has, don't bother reinstalling it.
  # We can also have faster builds by installing some libraries with
  # `apt`. If it isn't, install the GHC we want from hvr's PPA along
  # with cabal-1.18.
  - |
    if [ $GHCVER = `ghc --numeric-version` ]; then
      # Try installing some of the build-deps with apt-get for speed.
      travis/cabal-apt-install --enable-tests $MODE
      export CABAL=cabal
    else
      # Install the GHC we want from hvr's PPA
      travis_retry sudo add-apt-repository -y ppa:hvr/ghc
      travis_retry sudo apt-get update
      travis_retry sudo apt-get install cabal-install-1.22 ghc-$GHCVER happy
      export CABAL=cabal-1.22
      export PATH=/opt/ghc/$GHCVER/bin:$PATH
      ghc --version
    fi
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && $CABAL update
  - $CABAL update

  # Update happy when building with GHC head
  - |
    $CABAL install happy alex
    export PATH=$HOME/.cabal/bin:$PATH

install:
  - $CABAL install Cabal-1.22.4.0
  - $CABAL sandbox init
  - $CABAL install --dependencies-only --enable-tests --shadow-installed-packages
  - $CABAL configure -flib-Werror --enable-tests $MODE

script:
  - $CABAL build
  - $CABAL test --show-details=always

